language: node_js

node_js:
  - '6'

install:
  # install dependencies
  - set -e
  - npm install

script:
  # build and test
  - set -e
  - gulp test

deploy:
  provider: s3
  access_key_id:
    secure: "PjM3maAqcya/JpHk/CwfGY9h8YmjqC9gnWaFWYO+9HYZwEOvqOW+TWHsJIIKnUnOCZqddxrZPK9dCH4J5ccPdxO1kB0gImcowTw4UlN2cRAI60zhsLXzafO/l81Y8QuLTL5R3h8/tUka8LqT+v1mowaUQRNUppsKDToLSKrFa1mzds+q2zpwa+DqT6YmckVvONmS520czoPHCtkZJmqn8Ms4OO1oEAwRhPsyq3oqaA+E4gdNMr7d6o8i/Eb82SfVzGXxzRIbkzhG7HMtYGDH1rtQIVhbGtYwIVcush53YBHP+4foh/YBNh2+OR5KrteVyb33QxFwKukyHm79sktXV2qqcW/rRQTOfKWTZnvvXMf4/++pjaiEyK5vCcIIEL1UCFAXjqc3Vz29iPFgMWK0kg/r9ZeOC9YOyp/y0QhT14ISVTgkJ//mqqOLWVs3FFwBqurbK4oYlQHEeGXN67ta4KzpVQL/gxJdDCKWPM2J7fSP/kCtt4lgdObWdiBCN/R3/MqzPYVtRMmquGJIa56gALqLCjlkfzv/F0IJJ8Ge1WLWlw7t+HKLvUXWuTnmmPv3wJZLjn5jq9O6tcCl44FMDnRO3WO5owVn8k60riBOKn4FeA5gyNurayZJiRP8gtRW2yWsoCT/RlxM5U2bBHKiUEG5PGmlivDuerC6FHTBNBE="
  secret_access_key:
    secure: "AcsOEpP1jXlXWqvGcCTX7N/mQW17M0QgoKw18TdWjFMsEDX30cxe3cfgp696kRi4AdBhKGg52mbPJLgcCh3QgDCxqFoqDJDWouI9jbtghV5tpD6YpCu45ZghAx3LDCXybCPa6XU8X5KGtRBcwAHXafI7tek1Th0tQd0Ho3dI0HfXvG8QNtFdzOQ7BtisDM+hmof8Gi+YbDHSAQXrmD99bLDQXtZZWAjrv5VMoOHefgJ9UJg4xLvagmAB2o0ZbgwOC+koPWcPFeqqvrPrvnDMPwFo9T4z6dKyLozQUA0fc24U98h6GTKQHGE528xYVGrHjjgn9w93VpwYqdDC8pKAccr6mrXO+xyhu5g37Ph91qe5QApQUMT8yBRYZkSCzoLogC3dQR6cCilwRH1+97Q6MYCOMOtFBjFVLIPntaflZFXtWXOLQkDMle8nBPkM9XqH0Ui1wSkdu0ZLaZAy0S8CrayrJ9qU71fFZdjGYF53k/3+gu8v9bOx5EUVCeGliafMvoDhprHNhhQNrHk2VDIrE8vQmqxiKWOS3f4FWevI53CIYz1lAIJ555zIIv2N7rB3eh3lRr/00Zm3vW+4bMXYnnF70qEWeLO9d1IEGWwHtYWCw63HDdI/Fg9m2jbl3EFfdC11a8zIDW/SYp6YocBUq2+KztmsRGR75ycXMkfD5Ic="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: build/
  upload_dir: projects/chess/
